#!/usr/bin/env bash
# Раскатывает shared packages из workspace во все агент-репо.
#
# Запуск: из корня worldsim-workspace
#   ./repo-setup/sync-all.sh
#
# Что копируется:
#   packages/schemas/src/worldsim_schemas/   →  repos/<agent>/_schemas/
#   packages/prompts/src/worldsim_prompts/   →  repos/<agent>/_prompts/
#
# Каждая синкнутая папка получает:
#   - __header__.py  — предупреждение "не редактируй".
#   - .sync-manifest — SHA256 по всем синкнутым файлам, формат sha256sum -c.
#
# Drift детектится скриптом sync-check.sh — он перепроверяет хэши.

set -euo pipefail

WORKSPACE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REPOS_DIR="$(cd "${WORKSPACE_DIR}/.." && pwd)"
SCHEMAS_SRC="${WORKSPACE_DIR}/packages/schemas/src/worldsim_schemas"
PROMPTS_SRC="${WORKSPACE_DIR}/packages/prompts/src/worldsim_prompts"
AGENTS_FILE="${WORKSPACE_DIR}/repo-setup/agents.txt"

if [[ ! -d "${SCHEMAS_SRC}" ]]; then
  echo "Не найден ${SCHEMAS_SRC}" >&2
  exit 1
fi
if [[ ! -d "${PROMPTS_SRC}" ]]; then
  echo "Не найден ${PROMPTS_SRC}" >&2
  exit 1
fi

SCHEMAS_HEADER='"""
AUTO-GENERATED by worldsim-workspace/repo-setup/sync-all.sh — DO NOT EDIT.

Канонический источник: worldsim-workspace/packages/schemas/src/worldsim_schemas/

Любая правка тут перетрётся при следующем sync. Изменения делаются в
workspace, затем `./repo-setup/sync-all.sh`. CI-скрипт sync-check.sh падает,
если файлы здесь расходятся с манифестом.
"""
'

PROMPTS_HEADER='"""
AUTO-GENERATED by worldsim-workspace/repo-setup/sync-all.sh — DO NOT EDIT.

Канонический источник: worldsim-workspace/packages/prompts/src/worldsim_prompts/

Любая правка тут перетрётся при следующем sync. Изменения делаются в
workspace, затем `./repo-setup/sync-all.sh`. CI-скрипт sync-check.sh падает,
если файлы здесь расходятся с манифестом.
"""
'

# Пишет манифест SHA256 (формат sha256sum -c) всех файлов в каталоге,
# кроме самого .sync-manifest и __pycache__/*. Запускается из целевого каталога.
write_manifest() {
  local target="$1"
  (
    cd "${target}"
    find . -type f \
      -not -name .sync-manifest \
      -not -path '*/__pycache__/*' \
      | LC_ALL=C sort \
      | xargs sha256sum > .sync-manifest
  )
}

while IFS= read -r agent; do
  [[ -z "${agent}" ]] && continue
  [[ "${agent}" =~ ^# ]] && continue

  target="${REPOS_DIR}/${agent}"
  if [[ ! -d "${target}" ]]; then
    echo "! пропускаю ${agent} — папка ${target} не найдена"
    continue
  fi

  mkdir -p "${target}/_schemas" "${target}/_prompts"

  # Чистим старое содержимое (но не саму папку — она может быть в git)
  find "${target}/_schemas" -mindepth 1 -delete
  find "${target}/_prompts" -mindepth 1 -delete

  cp -R "${SCHEMAS_SRC}/." "${target}/_schemas/"
  cp -R "${PROMPTS_SRC}/." "${target}/_prompts/"

  # Убираем __pycache__, которые могли прилететь из editable-install источника.
  find "${target}/_schemas" "${target}/_prompts" -type d -name __pycache__ -prune -exec rm -rf {} +

  # AUTO-GENERATED заголовки
  printf '%s' "${SCHEMAS_HEADER}" > "${target}/_schemas/__header__.py"
  printf '%s' "${PROMPTS_HEADER}" > "${target}/_prompts/__header__.py"

  # Манифест хэшей (последним шагом — уже включает __header__.py)
  write_manifest "${target}/_schemas"
  write_manifest "${target}/_prompts"

  echo "✓ ${agent}"
done < "${AGENTS_FILE}"

echo ""
echo "Готово. Агент-репо теперь имеют свежие _schemas/ и _prompts/."
echo "Проверить отсутствие drift: ./repo-setup/sync-check.sh"
echo "Запустить тесты в каждом агенте: python -m pytest -q"
